# Generated by Django 5.1.4 on 2024-12-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=25)),
            ],
        ),
    ]
