# Generated by Django 5.1.4 on 2024-12-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0002_jar_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jar',
            options={'verbose_name': 'Банка', 'verbose_name_plural': 'Банки'},
        ),
        migrations.AlterModelTable(
            name='jar',
            table='jar',
        ),
    ]
