# Generated by Django 5.1.4 on 2024-12-24 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0003_alter_jar_options_alter_jar_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='JarOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Кількість грошей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('jar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jars.jar', verbose_name='Банка')),
            ],
        ),
    ]
