# Generated by Django 5.1.4 on 2024-12-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0004_jaroperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jar',
            name='slug',
            field=models.SlugField(default=1, max_length=155, unique=True, verbose_name='SLUG_URL'),
            preserve_default=False,
        ),
    ]
