# Generated by Django 5.1.4 on 2024-12-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0005_jar_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jaroperation',
            options={'verbose_name': 'Операція з банкою', 'verbose_name_plural': 'Операції з банкою'},
        ),
        migrations.AlterModelTable(
            name='jaroperation',
            table='jar_operations',
        ),
    ]
