# Generated by Django 5.1.4 on 2025-01-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0007_jaroperation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jar',
            name='status',
            field=models.CharField(choices=[('E', 'Пуста'), ('NF', 'Є гроші'), ('F', 'Заповнена')], default='E', max_length=2),
        ),
    ]
