# Generated by Django 5.1.4 on 2025-03-07 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0008_jar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jar',
            name='status',
            field=models.CharField(choices=[('E', 'Пуста'), ('F', 'Заповнена')], default='E', max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='jaroperation',
            name='jar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='jars.jar', verbose_name='Банка'),
        ),
    ]
