# Generated by Django 5.1.4 on 2024-12-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'db_table': 'tracker',
            },
        ),
    ]
