# Generated by Django 5.1.4 on 2024-12-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='data',
            new_name='date',
        ),
    ]
