# Generated by Django 5.1.4 on 2024-12-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_tracker_description_alter_tracker_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='amount',
            field=models.IntegerField(max_length=10, verbose_name='Количество'),
        ),
    ]
