# Generated by Django 5.1.4 on 2024-12-08 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_tracker_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва категорії')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='SLUG_URL')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'db_table': 'category',
            },
        ),
        migrations.AlterModelOptions(
            name='tracker',
            options={'verbose_name': 'Витрати', 'verbose_name_plural': 'Витрати'},
        ),
        migrations.AlterField(
            model_name='tracker',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category', verbose_name='Категорія'),
        ),
    ]
