# Generated by Django 5.1.4 on 2024-12-08 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_category_alter_tracker_options_alter_tracker_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='tracker.category', verbose_name='Категорія'),
        ),
    ]
