# Generated by Django 5.1.4 on 2024-12-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_tracker_amount_alter_tracker_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracker',
            new_name='Transaction',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='ransaction',
        ),
    ]
