# Generated by Django 5.1.4 on 2024-12-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_rename_tracker_transaction_alter_transaction_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], default='expense', max_length=20),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
