# Generated by Django 5.1.4 on 2024-12-09 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_transaction_transaction_type_alter_transaction_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакція', 'verbose_name_plural': 'Транзакції'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='operation',
            field=models.CharField(choices=[('income', 'Надходженя'), ('expense', 'Витрати')], default='income', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tracker.category', verbose_name='Категорія'),
        ),
    ]
