# Generated by Django 5.1.4 on 2024-12-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name': 'Транзакція', 'verbose_name_plural': 'Транзакції'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='operation',
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('income', 'Надходження'), ('expense', 'Витрати')], default='expense', max_length=8, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('income', 'Надходження'), ('expense', 'Витрати')], default='expense', max_length=8, verbose_name='Статус'),
        ),
    ]
