# Generated by Django 5.1.4 on 2024-12-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_transaction_options_remove_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
